$engine: 3
$onesync: on

name: Legacy Native Alpha
author: Legacy Framework
description: Installs Legacy Native Alpha (QB-free core, multichar, spawn, UI libs, analytics).

tasks:
  - action: connect_database

  - action: download_github
    src: https://github.com/stevecraine1994/legacy-native-alpha
    ref: main
    dest: ./temp/legacy

  - action: query_database
    file: ./temp/legacy/sql/legacy.sql

  - action: move_path
    src: ./temp/legacy/resources/[legacy]
    dest: ./resources/[legacy]

  - action: move_path
    src: ./temp/legacy/txadmin-recipe/server.cfg
    dest: ./server.cfg

  - action: remove_path
    path: ./temp/legacy
